### ISSUE TITLE
CC-BY for documents.

### ISSUE THREAD

**Issue by katyhuff** [arfc/ans-abs-template#2]
Since this is not software, I'd usually put this under a CC-BY license. I see you have put it under a BSD-3 type. Any particular reason @samgdotson ?

**Comment by samgdotson** [comment]
I wasn't entirely sure which license was needed so I defaulted to BSD-3. This is easily changed.

**Comment by katyhuff** [comment]
> I wasn't entirely sure which license was needed so I defaulted to BSD-3.

Cool. For future reference, I think BSD-3 is best for code, but CC-BY is more appropriate for written work (and static data, sometimes). 

> This is easily changed.

 Yes, please do.

**Comment by samgdotson** [comment]
I just remembered why I picked BSD-3, there isn't a CC-BY template license in GitHub only CC0. I will try copying the license from ``arfc.github.io``.
